name: Build

on:
  push:
    branches:
      - main
      - dev
      - "releases/**"
      - "feature/**"
      - "bugfix/**"
  pull_request:
    branches:
      - main
      - dev
      - "releases/**"
      - "feature/**"
      - "bugfix/**"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        run: ./gradlew clean :test:build -Pno-pandoc